version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: notes-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5433:5432"